### ISSUE TITLE
Running with SSNV data only

### ISSUE THREAD

**Issue by jonMitchGEL** [getzlab/deTiN#27]
I was wondering if and how it's possible to run deTiN using only SSNV data.

Running deTiN without any input produces the error message

"One of CN data or SSNV data are required."

implying that it should be possible to run with SSNV data only.  When I try this I get 

`Traceback (most recent call last):
  File "/home/jmitchell1/deTiN_env27/bin/deTiN", line 8, in <module>
    sys.exit(main())
  File "/home/jmitchell1/deTiN_env27/local/lib/python2.7/site-packages/deTiN/deTiN.py", line 462, in main
    di.read_and_preprocess_SSNVs()
  File "/home/jmitchell1/deTiN_env27/local/lib/python2.7/site-packages/deTiN/deTiN.py", line 195, in read_and_preprocess_SSNVs
    self.annotate_call_stats_with_allelic_cn_data()
  File "/home/jmitchell1/deTiN_env27/local/lib/python2.7/site-packages/deTiN/deTiN.py", line 172, in annotate_call_stats_with_allelic_cn_data
    self.call_stats_table['tau'] = tau
  File "/home/jmitchell1/deTiN_env27/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3370, in __setitem__
    self._set_item(key, value)
  File "/home/jmitchell1/deTiN_env27/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3444, in _set_item
    self._ensure_valid_index(value)
  File "/home/jmitchell1/deTiN_env27/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3424, in _ensure_valid_index
    value = Series(value)
  File "/home/jmitchell1/deTiN_env27/local/lib/python2.7/site-packages/pandas/core/series.py", line 262, in __init__
    raise_cast_failure=True)
  File "/home/jmitchell1/deTiN_env27/local/lib/python2.7/site-packages/pandas/core/internals/construction.py", line 658, in sanitize_array
    raise Exception('Data must be 1-dimensional')
Exception: Data must be 1-dimensional`

which looks like it's expecting the CN data. 

Is it poossible to run with the `--mutation_data_path` file only and if so do you have any suggestions as to what I might be doing wrong?

Thanks very much.

**Comment by amarotaylor** [comment]
Hey Jonathan 

I’m out of town this weekend I can take a look at this on Monday. If you need to move forward you could pass a dummy copy number file where the copy number is 2 and minor allele fraction is 0.5 for each segment. Without copy number data detin would make this assumption internally anyway. Hope that helps

**Comment by jonMitchGEL** [comment]
Thanks Amaro.  That's already very useful. The quick response is appreciated.
